sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedashfaq027/docker-react -f Dockerfile.dev .

script:
  - docker run ahmedashfaq027/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-w"
  app: "docker"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
